apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sysdig-certified
  namespace: sysdig
spec:
  channel: stable
  installPlanApproval: Automatic
  name: sysdig-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: sysdig-operator.v1.8.3
